updated ci script based on shell test script, launch tests in parallel for one flexisip, wait for db to launch before running server dans tests, set docker run options and test options in docker compose

diff --git a/.gitlab-ci-files/job-linux.yml b/.gitlab-ci-files/job-linux.yml
--- a/.gitlab-ci-files/job-linux.yml
+++ b/.gitlab-ci-files/job-linux.yml
@@ -134,15 +134,16 @@ tests-flexisip-mr:
     #Git branch to use to build the liblinphone_tester image. "release/${SDK_VERSION}" will be used as branch if empty.
     #SDK_BRANCH
     #Run test suites simultaneously.
-    PARALLEL_TEST_MODE: "false"
+    #PARALLEL_TEST_MODE: "false"
     #test flex-from-src instead of basic rpm dockerfile
     DOCKER_BUILD_OPTIONS: "--no-cache --force-rm -t gitlab.linphone.org:4567/bc/public/flexisip/flexisip:latest -f docker/flex-from-src --build-arg=njobs=12"
     liblinphone_tester: "gitlab.linphone.org:4567/bc/public/linphone-sdk/liblinphone_tester:$SDK_VERSION"
     sourcedir: ${CI_PROJECT_DIR}/linphone-sdk-docker
     workspace: "${CI_PROJECT_DIR}/liblinphone_tester_workspace"
     # we can't use $workspace nested variables here, since defined variables
-    # are extended in "script"
-    docker_run_options: "--volume=${CI_PROJECT_DIR}/liblinphone_tester_workspace:/home/bc/linphone-sdk-build/linphone-sdk/desktop/work --network=docker_default --device=/dev/snd --user 1000:29"
+    # are extended in "script".
+    # Useless run options are defined in docker-compose
+    #docker_run_options: "--volume=${CI_PROJECT_DIR}/liblinphone_tester_workspace:/home/bc/linphone-sdk-build/linphone-sdk/desktop/work --network=docker_default --device=/dev/snd --user 1000:29"
 
   before_script:
     ##
@@ -164,32 +165,10 @@ tests-flexisip-mr:
 
     - git clone -b feature/docker_liblinphone_tester --single-branch https://gitlab.linphone.org/BC/Public/linphone-sdk --recursive --jobs 12 linphone-sdk-docker
     - git clone -b conf/standalone-flexisip --single-branch git@gitlab.linphone.org:BC/Public/flexisip-tester --jobs 12
-    - |
-        if [ "$REBUILD_FLEXISIP_IMAGE_FROM_RPM" = "true" ]; then
-        docker build $DOCKER_BUILD_OPTIONS .
-        fi
-
-    - |
-        if [ "$REBUILD_SDK" = "true" ]; then
-        docker build --no-cache --force-rm -t gitlab.linphone.org:4567/bc/public/linphone-sdk/liblinphone_tester:$SDK_VERSION --build-arg="branch=$SDK_BRANCH" -f "$sourcedir/docker-files/liblinphone-tester" .
-        fi
-
-    - |
-        docker_compose_options=''
-        for name in 'docker-compose.yaml' 'docker-compose-standalone.yaml'; do
-        docker_compose_options="$docker_compose_options -f ${CI_PROJECT_DIR}/flexisip-tester/docker/$name"
-        done
-
-    - liblinphone_tester_options='--dns-hosts none --log-file liblinphone_tester.log --xml --verbose --show-account-manager-logs'
-
-    - |
-        if [ "$PARALLEL_TEST_MODE" = "true" ]; then
-        liblinphone_tester_options="$liblinphone_tester_options --parallel"
-        fi
-
-    - export FLEXISIP_LOGS="$workspace"
-
-    - mkdir -p $workspace/bin
+    - export FLEXISIP_DOCKER_IMAGE="gitlab.linphone.org:4567/bc/public/flexisip/flexisip"
+    - export FLEXISIP_DOCKER_TAG="latest"
+    - export LIBLINPHONE_DOCKER_IMAGE="gitlab.linphone.org:4567/bc/public/linphone-sdk/liblinphone_tester"
+    - export LIBLINPHONE_DOCKER_TAG=$SDK_VERSION
 
     - |
         if [ -z $workspace ]; then
@@ -197,7 +176,41 @@ tests-flexisip-mr:
         exit 1
         fi
 
+    - mkdir -p $workspace/bin
     - rm -rf $workspace/*
+
+    - |
+        if [ "$REBUILD_FLEXISIP_IMAGE_FROM_RPM" = "true" ]; then
+        docker build $DOCKER_BUILD_OPTIONS .
+        fi
+
+    - |
+        if [ "$REBUILD_SDK" = "true" ]; then
+        docker build --no-cache --force-rm -t gitlab.linphone.org:4567/bc/public/linphone-sdk/liblinphone_tester:$SDK_VERSION --build-arg="branch=$SDK_BRANCH" --build-arg="njobs=8" -f "$sourcedir/docker-files/liblinphone-tester" $sourcedir/docker-files/
+        fi
+
+    # Handle multiple runs by unsetting variable
+    # Overriding docker-compose.yaml values with docker-compose-standalone.yaml in the ways specified with docker docs (either OR or AND, depending on key)
+
+    - |
+        docker_compose_options=''
+        for name in 'docker-compose.yaml' 'docker-compose-standalone.yaml'; do
+        docker_compose_options="$docker_compose_options -f ${CI_PROJECT_DIR}/flexisip-tester/docker/$name"
+        done
+
+    #useless since tester options are defined in docker-compose
+
+    #- liblinphone_tester_options='--dns-hosts none --log-#file liblinphone_tester.log --xml --verbose --show-#account-manager-logs'
+
+    #- |
+    #    if [ "$PARALLEL_TEST_MODE" = "true" ]; then
+    #    liblinphone_tester_options="$liblinphone_tester_options --parallel"
+    #    fi
+    #########################################################
+
+    - export FLEXISIP_LOGS="$workspace"
+
+
     - cd $workspace
 
     - docker-compose $docker_compose_options down
@@ -206,11 +219,14 @@ tests-flexisip-mr:
         docker-compose $docker_compose_options build
         fi
 
-    - docker-compose $docker_compose_options up -d
+    # commented -d option to have debug logs on standard output in case of buggy or silent log artifacts
 
-    - sleep 60
+    - docker-compose $docker_compose_options up
 
-    - docker run $docker_run_options $liblinphone_tester $liblinphone_tester_options || EXIT=$? && echo 'Tests have failed'
+    # The sleep was removed because we now wait for the db socket to open (in compose file) before launching tests
+
+    # The tests are launched automatically from the compose file
+    #- docker run $docker_run_options $liblinphone_tester $liblinphone_tester_options || EXIT=$? && echo 'Tests have failed'
     - docker-compose $docker_compose_options stop
 
     - gzip *.log
@@ -232,7 +248,7 @@ tests-flexisip-mr:
     # args, we enter the entrypoint first, then the name of the image, then the
     # args to the entrypoint command.
     # "true ||" is used here to continue the script even if the find fails
-    - find . -type f -name "core*" | xargs -L1 docker run $docker_run_options --entrypoint gdb $liblinphone_tester ../bin/liblinphone_tester -x gdb_options || true
+    - if [[ -n $(find . -type f -name "core*") ]]; then find . -type f -name "core*" | xargs -L1 docker run $docker_run_options --entrypoint gdb $liblinphone_tester ../bin/liblinphone_tester -x gdb_options; fi || true
 
     # simplifing artifacts browsing
     # Moving artifacts to ease browsing from web view
