test run with specified versions of flexisip-auxiliaries, modified grep to exclude every docker-compose service but liblinphone_tester

diff --git a/.gitlab-ci-files/job-linux.yml b/.gitlab-ci-files/job-linux.yml
--- a/.gitlab-ci-files/job-linux.yml
+++ b/.gitlab-ci-files/job-linux.yml
@@ -150,59 +150,63 @@ tests-flexisip-mr:
       - $DEPLOY_UBUNTU
 
   variables:
-    #Build a new Flexisip Docker image from source
-    REBUILD_FLEXISIP_IMAGE: "false"
-    #Rebuild docker images of services which Flexisip needs to work: user
-    #  database, redis server, etc.
-    REBUILD_FLEXISIP_AUXILIARIES: "false"
-    #Set this option to true each time you change the commit to checkout for
-    #  linphone-sdk, otherwise, the SDK is never rebuild. default = true
-    REBUILD_SDK: "false"
-    SDK_VERSION: "4.3.3-46-g20b27fd"
-    SDK_BRANCH: "release/4.3"
+    #No need to modify
+    LIBLINPHONE_DOCKER_IMAGE: liblinphone_tester_for_flexisip
+
+    #You can set here the version you want for Flexisip auxiliaries and  liblinphone (branches with '/' are not supported yet since it is set as a docker tag).
+    #/!\ if you work with Lime-server, account-manager or file-transfer server dev packages, you MUST ensure that these packages are available in one of the BC snapshot repositories. Otherwize the docker images won't use the latest versions.
+    #You can use the latest version available of Lime-server, account-manager, file-transfer-server with the version number "latest"
+    #/!\ In this case, there MUST be NO image with the same name on the nuc, otherwize the docker images won't be rebuilt
+    LIBLINPHONE_DOCKER_TAG: "4.5.0-alpha-230-gb5ce1e7"
+    LIME_SERVER_VERSION: "1.0-27.el7"
+    ACCOUNT_MANAGER_VERSION: "1.1.0-36.el7"
+    FILE_TRANSFER_SERVER_VERSION: "1.0-5.el7"
+
+    #Branch of the Flexisip-tester project to use. Could be modified to test fixes or features in the Flexisip-tester
     FLEXISIP_TESTER_BRANCH: "master"
 
-    # uses flex-from-src instead of basic rpm dockerfile
-    DOCKER_BUILD_OPTIONS: "--no-cache --force-rm -t gitlab.linphone.org:4567/bc/public/flexisip/flexisip:latest -f docker/flex-from-src --build-arg=njobs=12"
-    liblinphone_tester: "gitlab.linphone.org:4567/bc/public/linphone-sdk/liblinphone_tester:$SDK_VERSION"
-    sourcedir: ${CI_PROJECT_DIR}/linphone-sdk-docker
+    #This value specifies the workspace where we from all tests outputs.
     workspace: "${CI_PROJECT_DIR}/liblinphone_tester_workspace"
 
+    #Flexisip docker image is build from source in the build stage (job docker-build-flexisip-src)
+    #No need to modify these values
     FLEXISIP_DOCKER_IMAGE: "gitlab.linphone.org:4567/bc/public/flexisip/flexisip-from-src"
     FLEXISIP_DOCKER_TAG: "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
 
     # Docker run options are only used for coredump display if any
     # We are forced to copy the same string as "workspace" because we can't use nested variables in the same place (i.e. in variable declaration)
     docker_run_options: "-v ${CI_PROJECT_DIR}/liblinphone_tester_workspace:/home/bc/linphone-sdk-build/linphone-sdk/desktop/work"
-
     flexisip_docker_run_options: "-v ${CI_PROJECT_DIR}/liblinphone_tester_workspace:/root"
-    # we can't use $workspace nested variables here, since defined variables
-    #   are extended in "script".
 
   script:
 
     - docker image ls
-    # used to ensure there will be not network name conflict for parallel
+    # used to ensure there will be not network name conflict for parallel 
     #   docker-compose executions
     - export COMPOSE_PROJECT_NAME=$RANDOM
     - echo $COMPOSE_PROJECT_NAME
 
-    - echo $SDK_BRANCH
-    - echo $liblinphone_tester
-    - echo $sourcedir
+    - export FLEXISIP_TESTER_SUBNET="2001:3200:3200:`printf '%x\n' $COMPOSE_PROJECT_NAME`::/64"
+    - echo "Flexisip tester private ipv6 subnet " $FLEXISIP_TESTER_SUBNET
+
+    - export FLEXISIP_TESTER_GATEWAY="2001:3200:3200:`printf '%x\n' $COMPOSE_PROJECT_NAME`::1"
+    - export FLEXISIP_TESTER_IPV6_PROBING_ADDR=$FLEXISIP_TESTER_GATEWAY
+    - echo "Flexisip tester private ipv6 gateway" $FLEXISIP_TESTER_GATEWAY
+    
+    - echo "Liblinphone tester version:" $LIBLINPHONE_DOCKER_TAG
     - echo $workspace
 
-    - |
-        if [ "$REBUILD_SDK" = "true" ]; then
-        git clone -b feature/docker_liblinphone_tester --single-branch https://gitlab.linphone.org/BC/Public/linphone-sdk --recursive --jobs 12 linphone-sdk-docker
-        docker build -t $liblinphone_tester --build-arg="branch=$SDK_BRANCH" --build-arg="njobs=8" -f "$PWD/linphone-sdk-docker/liblinphone-tester" .
-        fi
-    - id
-    - git clone -b $FLEXISIP_TESTER_BRANCH --single-branch git@gitlab.linphone.org:BC/Public/flexisip-tester --jobs 12
-    - echo $FLEXISIP_DOCKER_IMAGE
-    - echo $FLEXISIP_DOCKER_TAG
-    - export LIBLINPHONE_DOCKER_IMAGE="gitlab.linphone.org:4567/bc/public/linphone-sdk/liblinphone_tester"
-    - export LIBLINPHONE_DOCKER_TAG=$SDK_VERSION
+    - git clone -b $FLEXISIP_TESTER_BRANCH --single-branch git@gitlab.linphone.org:BC/private/flexisip-tester --jobs 12
+
+    #We make sure that the variables we set here can be accessed by the docker-compose scripts (in the flexisip-tester project).
+
+    - export FLEXISIP_DOCKER_IMAGE="$FLEXISIP_DOCKER_IMAGE"
+    - export FLEXISIP_DOCKER_TAG="$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
+    - export LIBLINPHONE_DOCKER_IMAGE=$LIBLINPHONE_DOCKER_IMAGE
+    - export LIBLINPHONE_DOCKER_TAG=$LIBLINPHONE_DOCKER_TAG
+    - export LIME_SERVER_VERSION="$LIME_SERVER_VERSION"
+    - export ACCOUNT_MANAGER_VERSION="$ACCOUNT_MANAGER_VERSION"
+    - export FILE_TRANSFER_SERVER_VERSION="$FILE_TRANSFER_SERVER_VERSION"
 
     - |
         if [ -z $workspace ]; then
@@ -219,43 +223,20 @@ tests-flexisip-mr:
     - sudo chown apache:apache $workspace
     - sudo chmod -R 777 $workspace
 
-    # /!\ We do not use docker-compose build because if we did the dockerfiles
-    #     location and the context can't be given as cli args but must be given
-    #     in docker-compose file.
-    #     Allowing it could be error-proning for anyone wanting to build
-    #     flexisip docker images only from flexisip-tester project
-
-    - |
-        if [ "$REBUILD_FLEXISIP_IMAGE" = "true" ]; then
-        docker build $DOCKER_BUILD_OPTIONS .
-        fi
-
-    - |
-        if [ "$REBUILD_SDK" = "true" ]; then
-        docker build --no-cache --force-rm -t gitlab.linphone.org:4567/bc/public/linphone-sdk/liblinphone_tester:$SDK_VERSION --build-arg="branch=$SDK_BRANCH" --build-arg="njobs=8" -f "$sourcedir/docker-files/liblinphone-tester" $sourcedir/docker-files/
-        fi
-
     # Handle multiple runs by unsetting variable
     # Overriding docker-compose.yaml values with docker-compose-standalone.yaml
     #   in the ways specified with docker docs (either OR or AND, depending on key)
 
     - |
-        docker_compose_options=''
+        docker_compose_options='--env-file /dev/null'
         for name in 'docker-compose.yaml' 'docker-compose-standalone.yaml'; do
         docker_compose_options="$docker_compose_options -f ${CI_PROJECT_DIR}/flexisip-tester/docker/$name"
         done
 
-    #useless since tester options are defined in docker-compose
-
-    #- liblinphone_tester_options='--dns-hosts none --log-file liblinphone_tester.log --xml --verbose --show-#account-manager-logs'
-
-    #- |
-    #    if [ "$PARALLEL_TEST_MODE" = "true" ]; then
-    #    liblinphone_tester_options="$liblinphone_tester_options --parallel"
-    #    fi
-    #########################################################
+    #Tester's options like parallel mode are defined in the docker-compose-standalone.yaml file of the flexisip-tester project
 
     - export FLEXISIP_LOGS="$workspace"
+    - export LIBLINPHONE_LOGS="$workspace"
 
     - export FLEXISIP_WORKSPACE="$workspace"
 
@@ -274,20 +255,26 @@ tests-flexisip-mr:
     # We output only liblinphone_tester on stdout
 
     #-V, --renew-anon-volumes   Recreate anonymous volumes instead of retrieving data from the previous containers.
-    - docker-compose $docker_compose_options up -V --exit-code-from liblinphone_tester | grep 'liblinphone_tester_1' || EXIT=$?
+    #--exit-code-from Exits with the return code from the specified container (implies --abort-on-container-exit)
+    #In the grep we are searching only for the logs related to liblinphone_tester and docker build, so we remove output from all other services.
 
-    # For each launched service, we print logs in seperate file with follow and timestamp options
+    - docker-compose $docker_compose_options up -V --exit-code-from liblinphone_tester |& tee logs_all | grep -v 'redis_server_1\|flexisip_1\|flexisip-regevent_1\|flexisip-external_1\|flexisip-external-domain_1\|lime-server_1\|lime-external-server\|dbserver_1\|account-manager_1\|file-transfer-server_1\|http-proxy_1' || EXIT=$?
+
+    #docker-compose log command isn't used anymore because of bad performance
+    #the logs were converted by docker in json format, then reconverted to txt, which is useless (doing this made the job last for 20-30 minutes for 9 minutes of tests)
+
     - |
         for service in $(docker-compose $docker_compose_options ps --services); do
-        echo $service
-        docker-compose $docker_compose_options logs -f -t $service >> ${service}_stdout.log
-        echo "docker-compose $docker_compose_options logs -f -t $service"
+        echo $service &
+        grep $service logs_all >> ${service}_stdout.log &
+        echo "grep $service logs_all" &
         done
 
-    # The sleep was removed because we now wait for the db socket to open (in compose file) before launching tests
+    #we wait for each grep to end before stopping containers
+    - wait
 
-    # The tests are launched automatically from the compose file
-    #- docker run $docker_run_options $liblinphone_tester $liblinphone_tester_options || EXIT=$? && echo 'Tests have failed'
+    # The sleep command was removed because we now wait for the db socket to open (in compose file) before launching tests
+
     - docker-compose $docker_compose_options stop
 
     - gzip *.log
@@ -300,6 +287,9 @@ tests-flexisip-mr:
 
   after_script:
 
+
+    - docker image ls
+
     #content of $workspace (set like this because the variable can't be resolved here)
     - cd ${CI_PROJECT_DIR}/liblinphone_tester_workspace
     # we specify commands to launch for each coredump of liblinphone_tester
@@ -311,11 +301,11 @@ tests-flexisip-mr:
     # The docker syntax is error proning : to override the entrypoint with
     # args, we enter the entrypoint first, then the name of the image, then the
     # args to the entrypoint command.
-    # "true ||" is used here to continue the script even if the find fails
-
+    # "|| true " is used here to continue the script even if the find fails
+    - FIND_EXIT=0
     - find . -type f -name "core.liblin*" | grep . || FIND_EXIT=$?
     - echo $FIND_EXIT
-    - if [[ $FIND_EXIT = 0 ]]; then find . -type f -name "core.liblin*" | xargs -L1 docker run $docker_run_options --entrypoint gdb $liblinphone_tester ../bin/liblinphone_tester -x gdb_options; fi || true
+    - if [[ $FIND_EXIT = 0 ]]; then find . -type f -name "core.liblin*" | xargs -L1 docker run $docker_run_options --entrypoint gdb "$LIBLINPHONE_DOCKER_IMAGE:$LIBLINPHONE_DOCKER_TAG" ../bin/liblinphone_tester -x gdb_options; fi || true
     - unset FIND_EXIT
     # we specify commands to launch for each coredump of flexisip_tester
     - echo "set debug-file-directory /opt/belledonne-communications/lib" | tee gdb_options
@@ -325,7 +315,7 @@ tests-flexisip-mr:
     - echo $FLEXISIP_DOCKER_IMAGE
     - echo $FLEXISIP_DOCKER_TAG
     - echo $flexisip_docker_run_options
-
+    - FIND_EXIT=0
     - find . -type f -name "core.flexisip*" | grep . || FIND_EXIT=$?
     - echo $FIND_EXIT
     - if [[ $FIND_EXIT = 0 ]]; then find . -type f -name "core.flexisip*" | xargs -L1 docker run $flexisip_docker_run_options --entrypoint gdb "$FLEXISIP_DOCKER_IMAGE:$FLEXISIP_DOCKER_TAG" /opt/belledonne-communications/bin/flexisip -x gdb_options; fi || true
